### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by wholmgren** [BXYMartin/Python-ClearSkyPy#4]
Thanks for sharing this interesting package. What is the license for the code? See "The Legal Side of Open Source" for why a license is needed before the community can use or modify the code. 

https://opensource.guide/legal/#why-do-people-care-so-much-about-the-legal-side-of-open-source

**Comment by BXYMartin** [comment]
Thank you for your notice, will do on the next update!

**Comment by BXYMartin** [comment]
MIT License added
