### ISSUE TITLE
downloading Merra2 data

### ISSUE THREAD

**Issue by glackner** [BXYMartin/Python-ClearSkyPy#5]
Hi, 

I have encountered a problem using irradpy when downloading data. I mostly want longwave downwelling radiation and precipitation thus I modified the section in example_downloader.py correspondingly:
 "rad": {
                    "esdt_dir": "M2T1NXRAD.5.12.4",
                    "collection": "tavg1_2d_rad_Nx",
                    "var_name": [ "SWGDN", "SWGDNCLR", "LWGNT", "LWGNTCLR"],
                    "standard_name": "radiation",
                    "least_significant_digit": 3,

                    },
		"flx": {
                    "esdt_dir": "M2T1NXFLX).5.12.4",
                    "collection": "tavg1_2d_flx_Nx",
                    "var_name": ["NIRDF", "NIRDR", "PRECTOTCORR"],
                    "standard_name": "fluxes",
                    "least_significant_digit": 3,

                    },

However, other variaboes are still downloaded from the aer, slv and asm collections and at some point I get the following error:
INFO:root:----  Begin  Download  ----
INFO:root:* File from Date 2017-01-01 Begin to Download
INFO:root:* File from Date 2017-01-01 Finished Download With 1.41 Seconds
CRITICAL:root:% New File from Date 2017-01-01 Integrity Check Failed
INFO:root:---- Download Finished ----
INFO:root:---- Begin Merging In Daily Variables ----
INFO:root:* Processing Data In 2017-01-01...
INFO:root:% Merging Data For MERRA2_400.tavg1_2d_aer_Nx.20170101.nc4.nc
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xarray-0.16.1-py3.6.egg/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/usr/local/lib/python3.6/dist-packages/xarray-0.16.1-py3.6.egg/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/gelac94/irradpy/Python-IrradPy-master/example/MERRA2_data/2017-1-1~2017-1-20 rad-slv-aer-asm [72,-80]~[74,-78]/MERRA2_400.tavg1_2d_aer_Nx.20170101.nc4.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

Any help with that is highly appreciated!
Thank you in advance,
Georg

**Comment by BXYMartin** [comment]
I noticed that you might have a typo for the `esdt_dir` in here:
`
"flx": {
                "esdt_dir": "M2T1NXFLX).5.12.4",
                "collection": "tavg1_2d_flx_Nx",
`

there is an extra ')', a quick fix would be:

`
"flx": {
                "esdt_dir": "M2T1NXFLX.5.12.4",
                "collection": "tavg1_2d_flx_Nx",
`

and it should work as expected!
